### ISSUE TITLE
Samsung SSD 950 PRO 512GB fails (almost) every command

### ISSUE THREAD

**Issue by ttDSSD-EMC** [MicronSSD/unvme#10]
Strangely, all command but identify seems to fail on my Samsung SSD 950 PRO 512GB.

unvme: 1a671ccc46ee9c305f1805865dc9c944b20db018 (current as of today)
Host: Supermicro X11SAE w/Xeon E3-1275
OS: Ubuntu 16.04 (kernel 4.4.0-31-generic, gcc version 5.4.0)

The output and log from a successful identify (ns = 1 works too but isn't shown)
https://gist.github.com/ttDSSD-EMC/e0dd1cd78ba0adc08425085482f02b78

Any attempt at anything else fails.  Here's a get log example
https://gist.github.com/ttDSSD-EMC/4e35e763ec9ead574adfe727bdf1ff14

In desparation I tried the experiments suggested under Issue #7 but they had no effect (hacks to r64() and -O0).

**Comment by sbradshawmicron** [comment]
Deyoung is out for a bit so responses may be delayed.

Do the admin cmds still fail if you change the NSID to 0?  Some controllers violate spec with respect to interpreting the NSID.

Maybe you could pull the error logs too?  One of the failed completions had the More bit set, suggesting some detail may be available in the logs.

**Comment by ttDSSD-EMC** [comment]
Thanks, I tried that, but unfortunately the _only_ command that seems to succeed is the identify.  In particular the get-log command fails for all arguments.  I tried the six [01] [123] combinations.  

There's nothing usual in syslog.  

It's not urgent, but I thought it mysterious and spent an hour trying to debug it.

**Comment by ttDSSD-EMC** [comment]
Some observations: Looks like the failure of the nvme_mts_test is different.  Both my target devices (Intel 750 IIRC and the Samsung 950 PRO) have (intentionally) never been used prior.  The Samsung reports 0 blockcount (nuse):

```
$ nvme_identify 7:0.0 1
Identify Namespace
==================
nsze    : 1000215216
ncap    : 1000215216
nuse    : 0
nsfeat  : 0
nlbaf   : 0
flbas   : 0
mc      : 0
dpc     : 0
dps     : 0
lbaf.0  : ms=0   lbads=9   rp=0  (formatted)
```

and that seems to break assumptions in the code.  I still haven't decided if this is expected or not.

**Comment by dhongMicron** [comment]
It looks like there is a problem with the drive.  If nuse is 0, UNVMe would fail to initialize.

However, for NVMe command examples, which is below the UNVMe layer, we've provided a couple examples of how to construct admin commands.  I don't have the Samsung 950 PRO drive, so I can't verify it.  Enabling UNVME_DEBUG to check the NVMe command and response, you can tell (as good as I can) if the command is correct or not, or the drive does or not conform to NVMe spec.

Sorry, I'm still on leave so I may be slow to respond.  Thanks.

**Comment by cinterloper** [comment]
I have a 950 PRO
I get the following output
```
$ test/unvme/unvme_sim_test 3e:00.0 (Fri Sep  2 11:30:08 MST 2016)
SIMPLE WRITE-READ-VERIFY TEST BEGIN
ERROR: vfio_create group not viable 0
ERROR: unvme_init vfio_create
ERROR: EXIT

$ sudo bash test/unvme-setup show
3d:00.0 Samsung Electronics Co Ltd NVMe SSD Controller - (mapped to nvme0)
3e:00.0 Samsung Electronics Co Ltd NVMe SSD Controller - (enabled for UNVMe)

# cat /dev/shm/unvme.log 
unvme_init 
ERROR: vfio_create group not viable 0
ERROR: unvme_init vfio_create
unvme_cleanup 

```
I am running an Intel SkullCanyon NUC
  *-core
       description: Motherboard
       product: NUC6i7KYB
       vendor: Intel Corporation

**Comment by dhongMicron** [comment]
What OS and kernel are you running?
$ cat /etc/system-release
$ uname -a

**Comment by cinterloper** [comment]
```
$ cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
$ uname -a
Linux g-skull 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dhongMicron** [comment]
According to Alex Williamson (vfio owner), group not viable error indicates failure to access vfio device descriptor, possibly due to another device in the same group binding to another driver. Try

% unvme-setup reset
% unvme-setup 3e:00.0

If that doesn't work, check Alex posting http://vfio.blogspot.com/2014/08/iommu-groups-inside-and-out.html.  This is a vfio configuration issue, so you can ask Alex how 2 of your devices are in the same group and how to separate them.

On my system with multiple NVMe devices, each device belongs to a separate iommu group, so they can work with different drivers.

**Comment by dhongMicron** [comment]
There are 2 different issues in this thread, and I want to check on the progress.  If you have info, please share, so others may benefit.

1)  Hi ttDSSD-EMC.
Regarding the Samsung 950 PRO reporting the nuse value of 0.  For some SSD, after formatting, nuse may be 0 until a namespace is explicitly created specifying its size (create-ns).  Have you found out whas the expected behavior for that drive is?  And for the admin commands, have you tried using the nvme commands from https://github.com/linux-nvme/nvme-cli.git?

2)  Hi cinterloper,
I'm assuming the "vfio_create group not viable" issue you have is due to certain configuration that does not allow 2 of your drives to use different drivers.  That should not be a problem if you run 'unvme-setup' without argument so both drives use the same driver.  Are they actually 2 physical SSDs or is it a virtual setup? 

Thanks.
